[package]
name = "gentlemen"
version = "0.1.0"
authors = ["Jonas Westlund <jonve547@student.liu.se>"]

[dependencies]
clippy = {version = "*", optional = true}
env_logger = "0.4.3"
error-chain = "*"
log = "0.3.8"
nom = "^3.0"

[features]
default = []
