cargo-features = ["edition"]
[package]
authors = ["Jonas Westlund <jonaswestlund101@gmail.com>"]
name = "blixt"
version = "0.1.0"
edition = "2018"
[dependencies]
failure = "0.1.0"
failure_derive = "0.1.1"
itertools = "0.7.8"
log = "0.3.8"
pretty_env_logger = "0.1.1"
termcolor = "0.3.6"
