[package]
authors = ["Jonas Westlund <jonve547@student.liu.se>"]
name = "gentlemen"
version = "0.1.0"
[dependencies]
failure = "0.1.0"
log = "0.3.8"
pretty_env_logger = "0.1.1"
failure_derive = "0.1.1"
itertools = "0.7.8"
